using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Mediator.SourceGenerators;

[Generator]
public class RequestIncrementalGenerator : IIncrementalGenerator
{
    private record Information(string Namespace, string GenericType, string FullyQualifiedClassName)
    {
        public string Namespace { get; } = Namespace;
        public string GenericType { get; } = GenericType;
        public string FullyQualifiedClassName { get; } = FullyQualifiedClassName;
    }
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
                static (ctx, _) => ctx is ClassDeclarationSyntax,
                static (ctx, _) => Transform(ctx))
            .Where(x => x.Found)
            .Select((x, _) => x.Info!);

        context.RegisterSourceOutput(context.CompilationProvider.Combine(provider.Collect()),
            (ctx, t) => GenerateCode(ctx, t.Left, t.Right));
    }


    private static (Information? Info, bool Found) Transform(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol typeSymbol)
            return (null, false);
        
        var result = GetInformationFromSymbol(typeSymbol, out var information);
        return (information, result);
    }
    
    private static bool GetInformationFromSymbol(INamedTypeSymbol symbol, out Information? information)
    {
        information = null;
        
        //foreach (var @interface in symbol.AllInterfaces)
        foreach (var @interface in symbol.AllInterfaces)
        {
            if (!@interface.Name.Contains("IRequestHandler") &&
                (@interface.BaseType is null || !@interface.BaseType.Name.Contains("IRequestHandler"))) continue;
            
            
            string interfaceName = @interface.ToString();
            int start = interfaceName.IndexOf('<');
            int end = interfaceName.LastIndexOf('>');
            interfaceName = interfaceName.Substring(start + 1,  end - start - 1);
                        
            information = new Information(symbol.ContainingNamespace.ToString(), interfaceName, symbol.ToString());
            return true;
        }
        
        // Tjek efter nested klasser

        return false;
    }

    private static void GenerateCode(SourceProductionContext context, Compilation compilation,
        ImmutableArray<Information> information)
    {
        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            foreach (var type in NotificationIncrementalGenerator.GetAllTypes(assembly.GlobalNamespace))
            {
                if (type.TypeKind != TypeKind.Class) continue;

                if (GetInformationFromSymbol(type, out var info) is false) continue;
                
                information = information.Add(info!);
            }
        }
        
        if (information.Length == 0) return;
        
        
        information = information.Distinct().ToImmutableArray();
        var namespaces = information.Select(x => x.Namespace).Distinct().ToArray();
        
        context.AddSource("MediatorHandlersDependencyInjection.g.cs",
            $$"""
              // <auto-generated/>
              
              using System;
              using Mediator.Interfaces;
              using Mediator.Helpers;
              using Microsoft.Extensions.DependencyInjection;
              using Microsoft.Extensions.DependencyInjection.Extensions;
              {{string.Join("\n", namespaces.Select(@namespace => $"using {@namespace};"))}}
              
              namespace Mediator.DependencyInjection;
              
              internal static class MediatorHandlerDependencyInjectionExtension
              {
                internal static MediatorBuilder AddHandlers(this MediatorBuilder builder)
                {
                    {{string.Join("\n\t\t", information.Select(info => $"builder.Services.TryAddTransient<IRequestHandler<{info.GenericType}>, {info.FullyQualifiedClassName}>();"))}}
                    
                    return builder;
                }
              }
              
              """);
    }
}